name: 'Mirror files to branches'
description: 'Mirror files to branches'

runs:
  using: composite
  steps:
    - name: Download the release, commit and push it to the branch
      run: |
        echo ${{ github.token }} | gh auth login --with-token
        ./mirror.sh
      shell: bash

    - name: Switch to the branch named main
      if: always()
      run: git switch --discard-changes main
      shell: bash
