#!/bin/bash

set -euo pipefail

for cmd in $(find download.d/ -type f); do
	branch=${cmd#*/}
	if [[ -n "$(git ls-remote origin refs/heads/$branch)" ]]; then
		echo "A branch name '$branch' already exists."
		continue
	fi

	bash -x $cmd
 	git switch --orphan "$branch"
	git add .
	git commit -m "Generated by the action named 'Mirror files to branches'"
	git push origin "$branch"
	git switch --discard-changes main
done
