#!/bin/bash

set -euo pipefail

for path in $(find download.d/ -name download.sh); do
	branch=$(dirname $path)
	branch=${branch#*/}
	if [[ -n "$(git ls-remote origin refs/heads/$branch)" ]]; then
		echo "A branch name '$branch' already exists."
		continue
	fi

	cmds=$(cat $path)
 	git switch --orphan "$branch"
	echo "$cmds" | bash 
	git add .
	git commit -m "Generated by the action named 'Mirror files to branches'"
	git push origin "$branch"
	git switch --discard-changes main
done
