#!/bin/bash

set -euo pipefail

for cmd in $(find download.d/ -name download.sh); do
	branch=$(dirname $cmd)
	if [[ -n "$(git ls-remote origin refs/heads/$branch)" ]]; then
		echo "A branch name '$branch' already exists."
		continue
	fi

 	git switch --orphan "$branch"
	bash $cmd
	git add .
	git commit -m "Generated by the action named 'Mirror files to branches'"
	git push origin "$branch"
	git switch --discard-changes main
done
